### ISSUE TITLE
Assuming schema_type: RECORD when using anyOf

### ISSUE THREAD

**Issue by dan-ladd** [adswerve/target-bigquery#17]
The following property:
`    "CreatedDate": {
      "anyOf": [
        {
          "type": "string",
          "format": "date-time"
        },
        {
          "type": [
            "string",
            "null"
          ]
        }
      ]
    }`

Results in a BQ schema of:
` SchemaField('CreatedDate', 'RECORD', 'NULLABLE', None, (), None)`

Because of this line in define_schema() https://github.com/adswerve/target-bigquery/blob/master/target_bigquery/schema.py#L153

I would expect something like:
`SchemaField('CreatedDate', 'TIMESTAMP', 'NULLABLE', None, (), None)` or maybe even just `SchemaField('CreatedDate', 'STRING', 'NULLABLE', None, (), None)`

This is from tap-salesforce, so I would be curious if you are running into this as well.

**PROPOSAL**:
It looks like we can handle this if we check the type in the first element of the anyOf and only assume a RECORD schema if the first non-null type is an object.
```
"BiddingScheme": {
        "anyOf": [
          {
            "type": [
              "null",
              "object"
            ],
            "additionalProperties": false,
            "properties": {
              "Type": {
                "type": [
                  "null",
                  "string"
                ]
              },
              "InheritedBidStrategyType": {
                "type": [
                  "null",
                  "string"
                ]
              }
            }
          }, ....```

**Comment by dan-ladd** [comment]
PR here: https://github.com/adswerve/target-bigquery/pull/18

**Comment by RuslanBergenov** [comment]
Hey Dan, thank you for your submission. 

Solution #1.

Our latest branch is `development ` and it has multiple improvements to how JSON schema is converted to BigQuery. 

The new branch handles this case, while outputting a string. I ran your unit test from dev branch: https://github.com/adswerve/target-bigquery/blob/hotfix/salesfoce/tests/test_schema.py#L675


Solution #2. 

In order to force a column to be a timestamp, we prefer to just specify it in catalog file:

```
          "CreatedDate": {
            "format": "date-time",
            "type": [
              "null",
              "string"
            ]
          }

```

**Comment by RuslanBergenov** [comment]
hi @dan-ladd, a third solution to your problem came to mind. The current master branch supports it.

If a column is of an undesired data type and the column is not following your tap-catalog file, you can force that column to the desired data type if you use force_fields flag inside your target-tables-config.json file.

Example of target-tables-config.json file where we force fields to a specific type and mode (example with tap facebook):
https://github.com/adswerve/target-bigquery/blob/development/tests/rsc/facebook_stream_tables_config.json

Here's how you would pass target tables config file (example with tap exchangeratesapi)
tap-exchangeratesapi --config sample_config/tap-exchange-rate-api.json | target-bigquery --config  sample_config/target-config.json -t sample_config/target-tables-config.json > sample_config/state.json

**Comment by RuslanBergenov** [comment]
We used this solution #3 described above with "date_start" field from "ads_insights_age_and_gender" stream from tap-facebook. In tap catalog file, we said we want this column to be date. The tap generates schema where this column is a string. Therefore, we use force_fields flag in target-tables-config.json to override that and force the column to be a date.

**Comment by dan-ladd** [comment]
Hey Ruslan Thanks for the follow up.

Solution 1)
I can't believe I didn't check the dev branch for this... Thanks for the heads up. It would be nice to have the format carry through. I will play around with this a bit more!

Solution 2)
This is what I have been doing (and instructing others to do), but for some taps, it means you have to manage all the catalogs and eliminates the possibility of using the tap's discovery capabilities. A pain when someone requests 40+ salesforce objects...

Solution 3)
This is very interesting and a good middle ground as it keeps you from having to manage the entire schema. I'd be interested in using this to force numerics as well!

Thanks again for your help, I will close this issue and PR.
